#!/bin/bash

set -e  # Exit on any error

# Initialize the chain if not already done
echo "Initializing simd chain..."
if [ ! -f /root/.simapp/config/genesis.json.backup ]; then
    # Initialize the chain with simd
    echo "Running: simd init simapp-validator --chain-id simapp-test --home /root/.simapp --overwrite"
    simd init simapp-validator --chain-id simapp-test --home /root/.simapp --overwrite

    # Only copy non-genesis config files from testapp_files
    echo "Copying non-genesis configuration files..."
    if [ -f /testapp_files/config/config.toml ]; then
        cp /testapp_files/config/config.toml /root/.simapp/config/
    fi
    if [ -f /testapp_files/config/app.toml ]; then
        cp /testapp_files/config/app.toml /root/.simapp/config/
    fi
    # Don't copy genesis.json - use the one generated by simd init

    # Copy data files if they exist
    cp -r /testapp_files/data/* /root/.simapp/data/ 2>/dev/null || echo "No custom data files to copy"

    # Mark as initialized
    touch /root/.simapp/config/genesis.json.backup
else
    echo "Chain already initialized, skipping init..."
fi

# Check if genesis file exists and has content
echo "Checking genesis file..."
if [ ! -f /root/.simapp/config/genesis.json ]; then
    echo "ERROR: Genesis file does not exist"
    exit 1
fi

GENESIS_SIZE=$(wc -c < /root/.simapp/config/genesis.json)
echo "Genesis file size: $GENESIS_SIZE bytes"

if [ "$GENESIS_SIZE" -lt 100 ]; then
    echo "ERROR: Genesis file is too small (probably empty or corrupted)"
    exit 1
fi

echo "Genesis file looks good (valid size and exists)"

# Add a validator to genesis if none exists
echo "Adding a validator to genesis..."

# Create a key for the validator
echo "Creating validator key..."
simd keys add validator --keyring-backend test --home /root/.simapp

# Add account to genesis
echo "Adding account to genesis..."
VALIDATOR_ADDR=$(simd keys show validator -a --keyring-backend test --home /root/.simapp)
simd add-genesis-account $VALIDATOR_ADDR 1000000000000stake --home /root/.simapp

# Create gentx
echo "Creating genesis transaction..."
simd gentx validator 1000000000stake --chain-id simapp-test --keyring-backend test --home /root/.simapp

# Collect gentxs
echo "Collecting genesis transactions..."
simd collect-gentxs --home /root/.simapp

# Final validation
echo "Validating genesis with simd..."
if ! simd validate-genesis --home /root/.simapp; then
    echo "ERROR: Genesis validation failed"
    exit 1
fi

echo "Genesis validation successful! Starting simd..."
exec simd start --home /root/.simapp --log_level info
