name: goreleaser
on:
  workflow_call:
    secrets:
      GORELEASER_ACCESS_TOKEN:
        required: true

jobs:
  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set GORELEASER_CURRENT_TAG in GitHub env
        if: github.event_name == 'release'
        run: echo "GORELEASER_CURRENT_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Create .release-env file
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' >> .release-env
      - name: Check the .goreleaser.yaml config file
        run: make goreleaser-check
        env:
          GORELEASER_CURRENT_TAG: ${{ env.GORELEASER_CURRENT_TAG }}

  goreleaser:
    needs: goreleaser-check
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && contains(github.ref, 'refs/tags/'))
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set GORELEASER_CURRENT_TAG in GitHub env
        if: github.event_name == 'release'
        run: echo "GORELEASER_CURRENT_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Create .release-env file
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' >> .release-env
      - name: Create prebuilt binaries and attach them to the GitHub release
        run: make prebuilt-binary
        env:
          GORELEASER_CURRENT_TAG: ${{ env.GORELEASER_CURRENT_TAG }}
