name: lint
on:
  workflow_call:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          # This job will pass without running if go.mod, go.sum, and *.go
          # wasn't modified.
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: v1.57.0
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
        if: env.GIT_DIFF

  # hadolint lints the Dockerfile
  hadolint:
    uses: celestiaorg/.github/.github/workflows/reusable_dockerfile_lint.yml@v0.4.1

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: celestiaorg/.github/.github/actions/yamllint@v0.4.1
