# this workflow runs tests
name: test

# this workflow runs on pushes to main and every pull request where a go.mod,
# go.sum or a *.go file has changed.
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: test
        run:
          go test -mod=readonly -timeout 30m ./...
        if: env.GIT_DIFF

  test-race:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: test
        run: >
          go test -mod=readonly -timeout 30m -race -test.short ./...
        if: env.GIT_DIFF
